<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '你确定要删除该项目？',
    'Delete' => '删除',
    'News' => '头条',
    'Save' => '保存',
    'Update' => '更新',
    'Update News: {nameAttribute}' => '',
    'Batch Deletion' => '批量删除',
    'Create News' => '创建头条',
    'Create success.' => '创建成功',
    'Created At' => '创建时间',
    'Delete News' => '删除头条',
    'Delete failed.' => '删除失败',
    'Delete success.' => '删除成功',
    'Description' => '描述',
    'Draft' => '草稿',
    'ID' => 'ID',
    'Manage News' => '头条管理',
    'Operation' => '操作',
    'Published' => '发布',
    'Published At' => '发布时间',
    'Rejected' => '拒绝',
    'Reset' => '重置',
    'Review' => '待审核',
    'Search' => '搜索',
    'Slug' => '标识',
    'Status' => '状态',
    'Title' => '标题',
    'Update News' => '更新头条',
    'Update success.' => '更新成功',
    'Updated At' => '更新时间',
    'Url' => 'Url地址',
    'User ID' => '用户ID',
    'Views' => '查看次数',
];
